'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ArrowDownToLine,ArrowUpRight,Columns2,Globe2,MapPin,MoveUpRight,Pause,Play,Sparkles,Waves} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import AtlasMap from '@/components/atlas-map';
import ModelComparison from '@/components/model-comparison';
import {formatNumber as fmt,histogram,type Aggregation,type Algorithm,type ExperimentIndex,type MapView,type Research} from '@/lib/research';
const aggLabels={median:'Median',mean:'Arithmetic mean',trimmed_mean:'Trimmed mean (10%)',robust:'Huber M-estimator'};
const algoLabels={spherical:'Spherical fit',classical:'Classical MDS',metric:'Metric MDS',nonmetric:'Non-metric MDS'};
const views:{id:MapView;name:string;icon:typeof Globe2}[]=[{id:'warped',name:'Warped Earth',icon:Globe2},{id:'displacement',name:'Displacement',icon:MoveUpRight},{id:'error',name:'Distance error',icon:Sparkles},{id:'uncertainty',name:'Uncertainty',icon:Waves},{id:'capitals',name:'Capitals',icon:MapPin}];
function Choice({label,value,options,onChange}:{label:string;value:string;options:{value:string;label:string}[];onChange:(v:string)=>void}){return <div className="choice"><span className="control-label">{label}</span><Select value={value} onValueChange={v=>{if(v!==null)onChange(v)}}><SelectTrigger aria-label={label}><SelectValue>{options.find(o=>o.value===value)?.label??value}</SelectValue></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
function Metric({label,value,unit}:{label:string;value:string;unit?:string}){return <div className="metric"><span>{label}</span><strong>{value}<small>{unit}</small></strong></div>}
const options=(x:Record<string,string>)=>Object.entries(x).map(([value,label])=>({value,label}));
const coordinate=(n:number|undefined,pos:string,neg:string)=>n===undefined?'—':`${fmt(Math.abs(n),2)}° ${n>=0?pos:neg}`;
export default function Home(){
 const [index,setIndex]=useState<ExperimentIndex[]>([]),[selected,setSelected]=useState(''),[data,setData]=useState<Research|null>(null),[error,setError]=useState('');
 const [aggregation,setAggregation]=useState<Aggregation>('median'),[algorithm,setAlgorithm]=useState<Algorithm>('spherical'),[view,setView]=useState<MapView>('warped'),[region,setRegion]=useState('All regions');
 const [amount,setAmount]=useState(1),[playing,setPlaying]=useState(false),[compare,setCompare]=useState(false),[pairA,setPairA]=useState('GB'),[pairB,setPairB]=useState('FR'),[hover,setHover]=useState('KE');
 const next=useRef<'a'|'b'>('a');
 const chooseCapital=useCallback((id:string)=>{if(next.current==='a'){setPairA(id);next.current='b'}else{setPairB(id);next.current='a'}setHover(id)},[]);
 useEffect(()=>{const c=new AbortController();fetch('/data/experiments.json',{signal:c.signal}).then(r=>{if(!r.ok)throw Error('No completed experiment has been published yet.');return r.json() as Promise<ExperimentIndex[]>}).then((items:ExperimentIndex[])=>{setIndex(items);if(items.length)setSelected(items.at(-1)!.id);else setError('No completed experiment has been published yet.')}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[]);
 useEffect(()=>{if(!selected)return;const c=new AbortController();setError('');setData(null);const entry=index.find(e=>e.id===selected);if(!entry)return;fetch(entry.url,{signal:c.signal}).then(r=>{if(!r.ok)throw Error('The research export could not be loaded. Please reload.');return r.json() as Promise<Research>}).then((r:Research)=>{setData(r);const ids=r.places.map(p=>p.id);setPairA(ids.includes('GB')?'GB':ids[0]);setPairB(ids.includes('FR')?'FR':ids[1]);setHover(ids.includes('KE')?'KE':ids[0]);setRegion('All regions')}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[selected,index]);
 useEffect(()=>{if(!playing)return;if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setPlaying(false);return}let frame=0;const start=performance.now();function tick(now:number){setAmount((1-Math.cos((now-start)/2200*Math.PI))/2);frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[playing]);
 useEffect(()=>{
  type Context={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>unknown};
  const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool||!data)return;const life=new AbortController();
  const register=(tool:Parameters<Context['registerTool']>[0])=>{try{void Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{/* Optional browser extension. */}};
  register({name:'inspect_capital_pair',description:'Read measured samples and statistics for two capital IDs.',inputSchema:{type:'object',properties:{a:{type:'string'},b:{type:'string'}},required:['a','b'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){const {a,b}=input as {a?:string;b?:string};const pair=data.pairs.find(p=>[p.place_a_id,p.place_b_id].includes(a??'')&&[p.place_a_id,p.place_b_id].includes(b??'')&&a!==b);if(!pair)throw Error('Choose two different capital IDs in this experiment');return pair}});
  register({name:'select_atlas_layer',description:'Select the visible aggregation and reconstruction.',inputSchema:{type:'object',properties:{aggregation:{type:'string',enum:Object.keys(aggLabels)},algorithm:{type:'string',enum:Object.keys(algoLabels)}},required:['aggregation','algorithm'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const x=input as {aggregation:string;algorithm:string};if(!Object.hasOwn(aggLabels,x.aggregation)||!Object.hasOwn(algoLabels,x.algorithm))throw Error('Unknown layer');setAggregation(x.aggregation as Aggregation);setAlgorithm(x.algorithm as Algorithm);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {experiment:data.experiment.id,...x}}});return()=>life.abort();
 },[data]);
 const pair=useMemo(()=>data?.pairs.find(p=>p.id===[pairA,pairB].sort().join('--')),[data,pairA,pairB]);
 const layer=data?.layers[aggregation],rec=layer?.reconstructions[algorithm],hi=data?.places.findIndex(p=>p.id===hover)??-1,place=data?.places[hi],city=layer?.capital_metrics[hi];
 const bins=histogram(pair?.samples??[]),root='/data/'+selected;
 return <main><header className="atlas-header"><a href="#" className="brand"><span>◉</span>Cognitive Atlas</a><nav><a href="#explore">Explore</a><a href="#method">Method</a><a href="#research-data">Research data <ArrowUpRight size={14}/></a></nav><span className="pilot-tag">{data&&data.places.length>20?'MODEL COMPARISON':'RESEARCH PILOT'}</span></header>
 <section className="intro"><div><span className="kicker">An experiment in elicited geography</span><h1>How does AI see the world?</h1><p>Ask for distances. Reconstruct the geometry. Explore the world implied by the answers.</p></div><div className="experiment-stamp"><span className="live-dot"/>{data?'Real Gemini responses':'Loading research'}<small>{data?new Date(data.experiment.created_at).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})+' · UTC':'CSV-backed · reproducible'}</small></div></section>
 {!data||!layer||!rec?<section className="surface loading" role="status"><Globe2 size={44}/><h2>{error||'Loading the reconstructed world…'}</h2><p>Only completed experiments with real model responses appear here.</p>{error&&<button onClick={()=>window.location.reload()}>Reload</button>}</section>:<>
 <section className="workspace" id="explore"><div className="toolbar"><Choice label="Experiment" value={selected} options={index.map(e=>({value:e.id,label:`${e.model_label??e.model.replace('gemini-','Gemini ')} · ${e.capital_count??20} capitals · ${e.language.toUpperCase()}`}))} onChange={setSelected}/><Choice label="Aggregate" value={aggregation} options={options(aggLabels)} onChange={v=>setAggregation(v as Aggregation)}/><Choice label="Reconstruction" value={algorithm} options={options(algoLabels)} onChange={v=>setAlgorithm(v as Algorithm)}/><Choice label="Region" value={region} options={['All regions',...new Set(data.places.map(p=>p.continent))].map(value=>({value,label:value}))} onChange={setRegion}/></div>
 <div className="workspace-body"><section className="map-surface"><div className="view-bar"><div className="view-options" aria-label="Map view">{views.map(v=><button key={v.id} aria-pressed={view===v.id} className={view===v.id?'active':''} onClick={()=>setView(v.id)}><v.icon size={15}/><span>{v.name}</span></button>)}</div><button className={'compare-button '+(compare?'active':'')} aria-label="Compare with actual Earth" aria-pressed={compare} onClick={()=>setCompare(!compare)}><Columns2 size={16}/><span>Compare</span></button></div>
 <div className={compare?'maps comparing':'maps'}>{compare&&<AtlasMap actual compact places={data.places} layer={layer} algorithm="spherical" amount={0} view="warped" region={region} selection={[pairA,pairB]} onSelect={chooseCapital} onHover={setHover}/>}<AtlasMap compact={compare} places={data.places} layer={layer} algorithm={algorithm} amount={amount} view={view} region={region} selection={[pairA,pairB]} onSelect={chooseCapital} onHover={setHover}/></div>
 <div className="morph"><button className="play-button" aria-label={playing?'Pause animation':'Animate Earth transformation'} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><button className="text-control" onClick={()=>{setPlaying(false);setAmount(0)}}>Actual Earth</button><Slider aria-label="Earth transformation" min={0} max={100} value={[amount*100]} onValueChange={v=>{setPlaying(false);setAmount((Array.isArray(v)?v[0]:v)/100)}}/><button className="text-control implied" onClick={()=>{setPlaying(false);setAmount(1)}}>Model-implied Earth</button><span className="mono">{Math.round(amount*100)}%</span></div>
 <div className="map-note">{algorithm==='spherical'?<>Distances are fitted on a sphere before projection. Coastlines are illustrative; <strong>{layer.mesh.foldovers} folded triangles</strong> at full strength.</>:<>Planar MDS uses a global Procrustes alignment to the projected reference. Coastlines are hidden; this is not a spherical reconstruction.</>}</div></section>
 <aside className="inspector"><div className="panel-heading"><span className="kicker">Capital inspection</span><MapPin size={15}/></div><h2>{place?.capital_name}</h2><p className="country-label">{place?.country_name} · {place?.continent}</p><div className="position-block"><span>Actual location</span><strong>{coordinate(place?.latitude,'N','S')}, {coordinate(place?.longitude,'E','W')}</strong></div>{algorithm==='spherical'&&<div className="position-block"><span>Aligned inferred location</span><strong>{coordinate(rec.inferred_latlon?.[hi]?.[0],'N','S')}, {coordinate(rec.inferred_latlon?.[hi]?.[1],'E','W')}</strong></div>}<div className="inspector-metrics"><Metric label={algorithm==='spherical'?'Displacement after alignment':'Reconstruction stress'} value={fmt(algorithm==='spherical'?rec.displacement_km?.[hi]:rec.stress,algorithm==='spherical'?0:4)} unit={algorithm==='spherical'?'km':''}/><Metric label="Mean error in related distances" value={fmt(city?.mae_km)} unit="km"/><Metric label="Mean within-pair variation" value={fmt((city?.mean_cv??0)*100,1)} unit="% CV"/></div><p className="small-note">Hover or focus a capital to inspect it. Select two capitals to explore their individual responses below.</p><div className="sample-note"><strong>{data.places.length} capitals</strong><span>{data.pairs.length} pairs · {data.experiment.sampling_count} samples each</span></div></aside></div>
 <div className="metric-strip"><Metric label="Mean absolute distance error" value={fmt(Number(layer.metrics.mae_km))} unit="km"/><Metric label="Distance rank correlation" value={fmt(Number(layer.metrics.spearman),4)}/><Metric label="Triangle violations" value={fmt(Number(layer.metrics.triangle_violation_rate)*100,2)} unit="%"/><Metric label={algorithm==='nonmetric'?'Ordinal stress':'Reconstruction stress'} value={fmt(rec.stress,4)}/><Metric label="Measured valid responses" value={fmt(data.quality.valid)}/></div></section>
 <ModelComparison selected={selected} aggregation={aggregation} onSelect={setSelected}/><section className="research-grid"><article className="panel pair-panel"><div className="panel-heading"><div><span className="kicker">Look inside the data</span><h2>Every answer, not just an average.</h2></div><span className="pill">Pair explorer</span></div><div className="pair-selectors"><Choice label="Capital A" value={pairA} options={data.places.map(p=>({value:p.id,label:p.capital_name}))} onChange={setPairA}/><span className="pair-arrow">↔</span><Choice label="Capital B" value={pairB} options={data.places.map(p=>({value:p.id,label:p.capital_name}))} onChange={setPairB}/></div>{pair?<><div className="pair-highlights"><Metric label="True WGS84 distance" value={fmt(pair.true_distance_km)} unit="km"/><Metric label={aggLabels[aggregation]} value={fmt(pair[aggregation])} unit="km"/><Metric label="Signed error" value={fmt((pair[aggregation]/pair.true_distance_km-1)*100,1)} unit="%"/></div><div className="histogram"><span className="control-label">Distribution of {pair.n} accepted responses</span><svg viewBox="0 0 500 130" role="img" aria-label={`Histogram of responses in kilometres: ${pair.samples.join(', ')}`}>{bins.map((b,i)=><g key={i}><rect x={25+i*450/bins.length} y={100-80*b.count/Math.max(...bins.map(x=>x.count))} width={450/bins.length-7} height={80*b.count/Math.max(...bins.map(x=>x.count))} rx="3" fill="#aaf078" opacity=".8"/><text x={25+(i+.5)*450/bins.length-3} y={92-80*b.count/Math.max(...bins.map(x=>x.count))} textAnchor="middle">{b.count}</text><text x={25+(i+.5)*450/bins.length-3} y="120" textAnchor="middle">{fmt((b.low+b.high)/2)}</text></g>)}</svg><div className="sample-values">{pair.samples.map((s,i)=><span key={i} title={`Accepted response ${i+1}`}>{fmt(s)}<small>km</small></span>)}</div></div><div className="pair-detail"><span>Mean <b>{fmt(pair.mean,1)} km</b></span><span>Median <b>{fmt(pair.median,1)} km</b></span><span>Standard deviation <b>{fmt(pair.std,1)} km</b></span><span>Variance <b>{fmt(pair.variance,1)} km²</b></span><span>MAD <b>{fmt(pair.mad,1)} km</b></span><span>Mean 95% bootstrap interval <b>{fmt(pair.mean_ci_low)}–{fmt(pair.mean_ci_high)} km</b></span></div>{pair.missing_samples>0&&<p className="warning">{pair.missing_samples} samples unavailable; all attempts remain in the CSV.</p>}</>:<p className="empty-message">Select two different capitals. Self-distances are zero by definition and were not queried.</p>}</article>
 <article className="panel dimension-panel"><span className="kicker">Does a flat world fit?</span><h2>The shape of the geometry</h2><p>Metric MDS residual stress at each dimensionality. A spherical Earth need not fit a Euclidean plane.</p><svg viewBox="0 0 400 220" role="img" aria-label="Metric MDS stress by dimensions"><g stroke="#2c3b50">{[0,.25,.5,.75,1].map(y=><path key={y} d={`M45 ${180-y*145}H380`}/>)}</g><path d={'M'+layer.dimensionality.map((d,i)=>`${45+i*335/(layer.dimensionality.length-1)},${180-d.stress*145}`).join('L')} fill="none" stroke="#aaf078" strokeWidth="2.5"/>{layer.dimensionality.map((d,i)=><g key={d.dimensions}><circle cx={45+i*335/(layer.dimensionality.length-1)} cy={180-d.stress*145} r="4" fill="#aaf078"><title>{d.dimensions}D: {d.stress.toFixed(5)} stress</title></circle><text x={45+i*335/(layer.dimensionality.length-1)} y="202" textAnchor="middle">{d.dimensions}</text></g>)}{[0,.5,1].map(y=><text key={y} x="30" y={184-y*145} textAnchor="end">{y}</text>)}</svg><div className="chart-axis">Embedding dimensions</div><div className="dimension-notes"><span>RMSE of pairwise estimates <b>{fmt(Number(layer.metrics.rmse_km))} km</b></span><span>Nearest-neighbour preservation <b>{fmt(Number(layer.metrics.nearest_neighbor_preservation_k3)*100,1)}%</b></span><span>Triangles tested <b>{fmt(Number(layer.metrics.tested_triangles))}</b></span></div><p className="small-note">Stress is a fitting diagnostic, not a measure of consciousness or a direct view inside the model.</p></article></section>
 <section className="method-section" id="method"><div><span className="kicker">What this experiment can tell us</span><h2>A map of judgments.<br/>A testable geometry.</h2><p>We ask about every pair in a fixed set of capitals. Each answer is a separate, tool-free conversation. Geometry is fitted to those answers, then globally aligned with Earth.</p></div><div className="method-steps"><div><span>01</span><h3>Elicit</h3><p>{data.experiment.model}, {data.experiment.language.toUpperCase()}. Temperature {data.experiment.parameters.temperature}, top-p {data.experiment.parameters.top_p}, thinking {data.experiment.parameters.thinking_level??`budget ${data.experiment.parameters.thinking_budget}`}. {data.experiment.sampling_count} independent samples per pair.</p></div><div><span>02</span><h3>Reconstruct</h3><p>Compare mean, median, trimmed mean, and Huber estimates. Fit spherical geometry or classical, metric, and ordinal MDS. No capital is individually forced toward its true position during fitting.</p></div><div><span>03</span><h3>Inspect</h3><p>The spherical fit uses global rotation or reflection only. The display deforms a triangular mesh between capital pins. Projection and coastline interpolation add their own visual distortions.</p></div></div></section>
 <section className="limitations"><h3>Read the map with its limits</h3><ul>{data.limitations.map(s=><li key={s}>{s}</li>)}</ul><p>Provider model versions are recorded with each response. Saved outputs can be reanalysed; calling the same model again is not guaranteed to produce identical answers.</p></section>
 <section className="downloads" id="research-data"><div><span className="kicker">Open the evidence</span><h2>Take the experiment with you.</h2><p>Raw responses, exact conditions, fitted coordinates, and distance matrices.</p><code>{data.experiment.id}</code></div><div className="download-links">{[['responses.csv','Raw responses · CSV'],['pair_statistics.csv','Pair statistics · CSV'],['coordinates.csv','Reconstructed coordinates · CSV'],[`matrix-${aggregation}.csv`,'Selected distance matrix · CSV'],['matrix-truth.csv','WGS84 distances · CSV'],['manifest.json','Experiment manifest · JSON'],['result.json','Complete analysis · JSON']].map(([file,label])=><a key={file} href={`${root}/${file}`} download><span>{label}</span><ArrowDownToLine size={17}/></a>)}</div></section>
 <footer><span>◉ Cognitive Atlas</span><span>{data.quality.attempts} recorded attempts · {data.quality.invalid_attempts} flagged · token-based cost estimate ${fmt(data.quality.estimated_cost_usd,4)}</span><a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Map data: Natural Earth</a></footer></>}
 </main>
}
